# Project information
site_name: Wireless communications

site_description: 'Documentation of wireless communications'
site_author: 'Willem Dekker, Ruben Smit'

# Copyright
copyright: Copyright &copy; 2021 Ruben Smit, Willem Dekker

# Congiguration
theme:
  name: material
  features:
    - navigation.tabs
  palette:
    scheme: preference
  language: nl
plugins:
  - search:
      lang: nl
  - with-pdf:
        #author: WHO
        #copyright: ANY TEXT
        #
        #cover: false
        back_cover: true
        #cover_title: TITLE TEXT
        cover_subtitle: IOT specialization | HBO-ICT Software Engineering
        #custom_template_path: TEMPLATES PATH
        #
        #toc_title: TOC TITLE TEXT
        #heading_shift: false
        #toc_level: 3
        #ordered_chapter_level: 2
        #excludes_children:
        #    - 'release-notes/:upgrading'
        #    - 'release-notes/:changelog'
        #
        #exclude_pages:
        #    - 'bugs/'
        #    - 'appendix/contribute/'
        #convert_iframe:
        #    - src: IFRAME SRC
        #      img: POSTER IMAGE URL
        #      text: ALTERNATE TEXT
        #    - src: ...
        #two_columns_level: 3
        #
        #render_js: true
        #headless_chrome_path: headless-chromium
        #
        #output_path: any-place/document.pdf
        #enabled_if_env: ENABLE_PDF_EXPORT
        #
        #debug_html: true
        #show_anchors: true
        #verbose: true
