# Project information
site_name: Wireless communications

site_description: 'Documentation of wireless communications'
site_author: 'Willem Dekker, Ruben Smit'

# Copyright
copyright: Copyright &copy; 2021 Ruben Smit, Willem Dekker

# Congiguration
theme:
  name: material
  features:
    - navigation.tabs
  palette:
    scheme: preference
  language: nl
plugins:
  - search:
      lang: nl